server {
    listen       8080;
    server_name  localhost; # 在 Docker 中通常用 localhost 或具体 IP

    # 容器内的路径，对应下面 docker run 映射的目标路径
    root   /usr/share/nginx/html;
    index  index.html;

    # Gzip 压缩
    gzip            on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types      text/plain text/css text/javascript application/javascript application/json image/svg+xml;
    gzip_vary       on;

    # 静态资源长期缓存
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA 路由回退
    location / {
        try_files $uri $uri/ /index.html;
        
        # 禁止缓存 index.html
        if ($request_filename ~* index\.html$) {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }
}